### PR TITLE
Fix big endian for PowerPC

### LINKED ISSUE #75: test.bytes fails on PPC: endianness is ignored
```

R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: powerpc-apple-darwin10.8.0 (32-bit)

> library("testthat")
> library("pryr")
> 
> test_check("pryr")
[ FAIL 4 | WARN 0 | SKIP 0 | PASS 61 ]

══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test-bytes.r:5'): bytes produces hex representations as expected ──
bytes(1L) not identical to c("00 00 00 01").
1/1 mismatches
x[1]: "01 00 00 00"
y[1]: "00 00 00 01"
── Failure ('test-bytes.r:10'): bytes produces hex representations as expected ──
bytes(1) not identical to "3F F0 00 00 00 00 00 00".
1/1 mismatches
x[1]: "00 00 00 00 00 00 F0 3F"
y[1]: "3F F0 00 00 00 00 00 00"
── Failure ('test-bytes.r:24'): bytes produces binary representations as expected ──
bits(1L) not identical to "00000000 00000000 00000000 00000001".
1/1 mismatches
x[1]: "00000001 00000000 00000000 00000000"
y[1]: "00000000 00000000 00000000 00000001"
── Failure ('test-bytes.r:29'): bytes produces binary representations as expected ──
bits(1) not identical to "00111111 11110000 00000000 00000000 00000000 00000000 00000000 00000000".
1/1 mismatches
x[1]: "00000000 00000000 00000000 00000000 00000000 00000000 11110000 00111111"
y[1]: "00111111 11110000 00000000 00000000 00000000 00000000 00000000 00000000"

[ FAIL 4 | WARN 0 | SKIP 0 | PASS 61 ]
Error: Test failures
Execution halted
```

### PR DESCRIPTION
**Pull request by barracuda156**
Fixes: https://github.com/hadley/pryr/issues/75

### CODE REVIEW

**Comment by barracuda156** [comment]
@hadley This should be uncontroversial to merge. Tests pass now without errors.

**Comment by barracuda156** [comment]
@hadley Any chance of having this merged?

**Comment by hadley** [comment]
pryr is superseded and archived on CRAN. So while I can certainly merge this PR, I'm not sure what it would achieve more broadly.

**Comment by barracuda156** [comment]
@hadley I you don’t mind, that is still helpful. There are packages using `pryr` (and some perhaps won’t be moved to anything else), and in Macports we can use your version from GitHub and drop the patch. Potentially it may be useful for someone who will need it work on Big-endian Linux or BSD too.

**Pull request merged**
